version: "3.8"

services:
  mongo:
    image: mongo
    container_name: musicplayerlibrary-mongo

    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: .
    container_name: musicplayerlibrary-backend

    depends_on:
      - mongo
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ../music-player # Specify the build context to the frontend folder
    container_name: musicplayerlibrary-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data:
